source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MaterialDesignUITextField_Example', :exclusive => true do
  pod "MaterialDesignUITextField", :path => "../"
end

target 'MaterialDesignUITextField_Tests', :exclusive => true do
  pod "MaterialDesignUITextField", :path => "../"

  
end
